//! Embedding type definition.
//!
//! Embeddings are vector representations of text used for similarity search.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Vector representation of text.
///
/// Embeddings are dense vector representations generated by embedding models.
/// They are used for semantic similarity search in the RAG pipeline.
///
/// # Example
///
/// ```rust
/// use edgequake_core::types::Embedding;
///
/// let embedding = Embedding::new(
///     "emb-123".to_string(),
///     vec![0.1, 0.2, 0.3],
///     Some("Sample text".to_string()),
/// );
/// assert_eq!(embedding.dimension(), 3);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Embedding {
    /// Unique identifier
    pub id: String,
    /// Dense vector representation
    pub vector: Vec<f32>,
    /// Original text that was embedded
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Additional metadata
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub metadata: HashMap<String, serde_json::Value>,
}

impl Embedding {
    /// Create a new embedding.
    ///
    /// # Arguments
    ///
    /// * `id` - Unique identifier for this embedding
    /// * `vector` - The dense vector representation
    /// * `content` - Optional original text that was embedded
    pub fn new(id: String, vector: Vec<f32>, content: Option<String>) -> Self {
        Self {
            id,
            vector,
            content,
            metadata: HashMap::new(),
        }
    }

    /// Create a new embedding with metadata.
    pub fn with_metadata(
        id: String,
        vector: Vec<f32>,
        content: Option<String>,
        metadata: HashMap<String, serde_json::Value>,
    ) -> Self {
        Self {
            id,
            vector,
            content,
            metadata,
        }
    }

    /// Get the dimension of the embedding vector.
    pub fn dimension(&self) -> usize {
        self.vector.len()
    }

    /// Calculate the cosine similarity with another embedding.
    ///
    /// Returns a value between -1 and 1, where 1 means identical direction.
    ///
    /// # Panics
    ///
    /// Panics if the embeddings have different dimensions.
    pub fn cosine_similarity(&self, other: &Embedding) -> f32 {
        assert_eq!(
            self.dimension(),
            other.dimension(),
            "Embeddings must have the same dimension"
        );

        let dot_product: f32 = self
            .vector
            .iter()
            .zip(other.vector.iter())
            .map(|(a, b)| a * b)
            .sum();

        let norm_a: f32 = self.vector.iter().map(|x| x * x).sum::<f32>().sqrt();
        let norm_b: f32 = other.vector.iter().map(|x| x * x).sum::<f32>().sqrt();

        if norm_a == 0.0 || norm_b == 0.0 {
            0.0
        } else {
            dot_product / (norm_a * norm_b)
        }
    }

    /// Calculate the Euclidean distance to another embedding.
    ///
    /// # Panics
    ///
    /// Panics if the embeddings have different dimensions.
    pub fn euclidean_distance(&self, other: &Embedding) -> f32 {
        assert_eq!(
            self.dimension(),
            other.dimension(),
            "Embeddings must have the same dimension"
        );

        self.vector
            .iter()
            .zip(other.vector.iter())
            .map(|(a, b)| (a - b).powi(2))
            .sum::<f32>()
            .sqrt()
    }

    /// Normalize the embedding vector to unit length.
    pub fn normalize(&mut self) {
        let norm: f32 = self.vector.iter().map(|x| x * x).sum::<f32>().sqrt();
        if norm > 0.0 {
            self.vector.iter_mut().for_each(|x| *x /= norm);
        }
    }

    /// Get a normalized copy of this embedding.
    pub fn normalized(&self) -> Self {
        let mut copy = self.clone();
        copy.normalize();
        copy
    }

    /// Add metadata to the embedding.
    pub fn set_metadata(&mut self, key: impl Into<String>, value: serde_json::Value) {
        self.metadata.insert(key.into(), value);
    }

    /// Get metadata value by key.
    pub fn get_metadata(&self, key: &str) -> Option<&serde_json::Value> {
        self.metadata.get(key)
    }
}

/// Configuration for embedding generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingConfig {
    /// Vector dimension (e.g., 1536 for OpenAI ada-002)
    pub embedding_dim: usize,
    /// Maximum tokens per text
    pub max_token_size: usize,
    /// Model name for the embedding provider
    pub model_name: String,
    /// Batch size for embedding generation
    pub batch_size: usize,
}

impl Default for EmbeddingConfig {
    fn default() -> Self {
        Self {
            embedding_dim: 1536,
            max_token_size: 8192,
            model_name: "text-embedding-3-small".to_string(),
            batch_size: 100,
        }
    }
}

impl EmbeddingConfig {
    /// Create a new embedding configuration.
    pub fn new(embedding_dim: usize, max_token_size: usize, model_name: String) -> Self {
        Self {
            embedding_dim,
            max_token_size,
            model_name,
            batch_size: 100,
        }
    }

    /// Create configuration for OpenAI text-embedding-3-small model.
    pub fn openai_small() -> Self {
        Self {
            embedding_dim: 1536,
            max_token_size: 8191,
            model_name: "text-embedding-3-small".to_string(),
            batch_size: 100,
        }
    }

    /// Create configuration for OpenAI text-embedding-3-large model.
    pub fn openai_large() -> Self {
        Self {
            embedding_dim: 3072,
            max_token_size: 8191,
            model_name: "text-embedding-3-large".to_string(),
            batch_size: 100,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_embedding_creation() {
        let emb = Embedding::new(
            "test".to_string(),
            vec![1.0, 0.0, 0.0],
            Some("hello".to_string()),
        );

        assert_eq!(emb.id, "test");
        assert_eq!(emb.dimension(), 3);
        assert_eq!(emb.content, Some("hello".to_string()));
    }

    #[test]
    fn test_cosine_similarity() {
        let emb1 = Embedding::new("1".to_string(), vec![1.0, 0.0, 0.0], None);
        let emb2 = Embedding::new("2".to_string(), vec![1.0, 0.0, 0.0], None);
        let emb3 = Embedding::new("3".to_string(), vec![0.0, 1.0, 0.0], None);

        // Identical vectors
        let sim1 = emb1.cosine_similarity(&emb2);
        assert!((sim1 - 1.0).abs() < 1e-6);

        // Orthogonal vectors
        let sim2 = emb1.cosine_similarity(&emb3);
        assert!(sim2.abs() < 1e-6);
    }

    #[test]
    fn test_euclidean_distance() {
        let emb1 = Embedding::new("1".to_string(), vec![0.0, 0.0, 0.0], None);
        let emb2 = Embedding::new("2".to_string(), vec![1.0, 0.0, 0.0], None);

        let dist = emb1.euclidean_distance(&emb2);
        assert!((dist - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_normalization() {
        let mut emb = Embedding::new("1".to_string(), vec![3.0, 4.0], None);
        emb.normalize();

        let norm: f32 = emb.vector.iter().map(|x| x * x).sum::<f32>().sqrt();
        assert!((norm - 1.0).abs() < 1e-6);
    }

    #[test]
    fn test_metadata() {
        let mut emb = Embedding::new("1".to_string(), vec![1.0], None);
        emb.set_metadata("key", serde_json::json!("value"));

        assert_eq!(emb.get_metadata("key"), Some(&serde_json::json!("value")));
        assert_eq!(emb.get_metadata("missing"), None);
    }

    #[test]
    fn test_embedding_config() {
        let config = EmbeddingConfig::openai_small();
        assert_eq!(config.embedding_dim, 1536);
        assert_eq!(config.model_name, "text-embedding-3-small");

        let config_large = EmbeddingConfig::openai_large();
        assert_eq!(config_large.embedding_dim, 3072);
    }
}
